const express=require('express')
const router=express.Router()
const cakeController =require('../Controllers/cake.controller')
router.put("/:id",cakeController.updateCake)
router.delete("/:id",cakeController.deleteCake)
router.post("/create",cakeController.createCake)
router.get("/search",cakeController.getCakesByNameAndCategory)
router.get("/:id",cakeController.getCakeById)
router.get("/",cakeController.getCakesByPagination)
module.exports=router